sudo: required

language: go

go:
  - 1.6

services:
  - docker

env:
  global:
    - GO15VENDOREXPERIMENT=1
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: "QRKwhNOcGy/l9Z+4Sqra5UVB2fETqBe8K3kxZ8oiX1Hnt5054Hqw/fmCUADgtKgEmtinvvbJofyzfPh1Mvx52h9W1U27vCnMo8Gm1YQfU4CEIzm/L3pKZ9DjR4X87Vhfz4//3rrltBgpu/lDMbhtczSyhxmvbLsDqToiHnkPrmaeOdeV9y+G6vETH/n8YaYhX19fKvSh/4gUXp9/ljhxm1oWXpszci0q5ABK6n8sb5JR46c9NQ3zZFUmXq7i5AkemUycfAtJvzDFeQIwxMlPV85zFXR5nHGBzmF5AVjJW97K3HMX7CtPeamCEQc348ah/g3NO+dUyA691AgLUxue8pf//uYtSM18YBXH81mk4BDRJObN2lK2mTOjsPnef2oX7K+mf3bmFFOgdcM7n418Q14C2WLT4rips4Vh3okJH+2FqpyLk9IRVZywmi8dJYsGOWToBiOcQPAbmMgYtNYtcGBbSjq9h+B2AuDO3KeWeeMKMHn3UONWfT8rBQuYk4LQ8Jz/lJTRvJjzOK+pDXhOjcqPKeDyDvb0uEwsGxN1ojf9OPWyPafWraBv0G6aIP+nS/5qhfdMbCDo8b78m1zWIY+vyDHcdz2+jMkj/OqTi7OQT/Q8y9KwPVdZiEi2sZWiCWeDh34ksEJ0j0NJFOXyREscxzDzUjGJVXQo7qHikkQ=" # DOCKER_EMAIL
    - secure: "MGwibmz/SKiwqA++P1S/NfgKgTzFANjhTe2iAFg9Hzo0tFi9XI2byFLV9PoymLMO+BsOMrqi9ghaqKnJVc3Qm1atSbl8mvwofYIiu2EMteiDcdRdRl8ejBxKceI3kPhv4D58kGi985LDCta5JelC6HrCCp5U6jIC2pcRZ2reZ9H+5nrU1aax4gf2x/qdkJF6ny9YoAgISVtYYOQ5BTp0fe7UDcQkgsfkfSa7yN0+YM0cZ/wkBs9ZpSlaxenFQjm6yZ09R9t3WNwCWt1BWEwD3YvRBj3KxMUtVR8orW3u/StGrNLMMQN4B7erNxri7y/OCyebH0Icr+IsWTyTDimrGX0jUuA24PLjiIneCpAl5ZxuIIxaSE1GabKGjk4J8vOLXEOkgo8Dr8QNc95MKXuQn2KNE1uWglCILODO/5QKyMNTdmNe+1u1E04a5uMBSm7pRnBbjSlJBCRpstcCqZPcWxg4ReB5bgG3E1aIsf75uy6Bb9ax7IWXs9NYr3BVMfgbXp3qmmEvX4RtVVnPNhl1Tk/Q18meglfeyU1bNoEddC8iWU5jHeHJFG+wDJcZieYRzvCmglPCGeLvvTsbGgEiKT+p76Wk+HByJ0v5TR8LcyuzJXYah2ioYygP32YI1ZXxw6d9UrxnGa8dHGd92PAsy7xBmPUDm4kISLK9ERUGOqo=" # DOCKER_USER
    - secure: "EQZmXnxPg/ce6w2AgX6zUbyAL87kFHhMxCilHsegaX3mMOufJZs/W9ec2FEeXDpRVv53AZ8II221WRtckOM9qsmW5gaUXROPvDkPlqTRHrW0z5hmTGRLBDq4cH87W8grYuarqfDyPw3TJMOZrfThS/ZAWy8MeEz72FX4wvkkDOEmLVVxFhm9h9IXlIQnG3XHJI7zP2hSBQldhMX+FA21gNiJAux/VPtEt5CkE3HeueTHu/bMRAuDiQ198yWwOZu21PKbMxH9IddZx6PQIVfSVa6lRLOqHT0p6bBymwJJ4UeY0wOXCrDknDDuuOntZ5cd5d1SpRTooSDa2DL6x6dQ9ieBFoJYqDiRJ8R8ZNjF61BHsF511NnsntIqSp9GblsU5K8sWmgdqNwgE5H+l/Zjda4QlkH4YVjM073AVwypvWiSkPcHwXVeqxUX0np2CuL80jhHV5tV4b5ZUIomv7ulLqqgR8CrZOXrAE5CHKixvlK5lnZF8ZEFEkpr6Zs1IqoxO48MzMx+SLRBXjMYGIkG3bSsPX5Gy1xMy4jfaCa4bsFpnxQtCmFRzCtBu+8XJzk0sob692Ve0hu4AqreiEOpPRRZBi7wr5os3MEYgB1YOlUGzy9eF4KVJyJ+Zd/R9HXuAXl0a10Q4okosUZwwNuPKPJUuXBC1nSZXFWx+I6ZBUI=" # DOCKER_PASS

install:
  - make install

script:
  - make test
  - timeout 5 docker-compose logs || true

after_success:
  - export REPO=crossdock/crossdock
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH; fi`
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, REPO=$REPO, PR=$PR, BRANCH=$BRANCH, TAG=$TAG"
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
  - docker build -f Dockerfile.scratch -t $REPO:$COMMIT .
  - docker run $REPO:$COMMIT
  - docker images
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
