crossdock:
    build: .
    links:
        - alpha
        - omega
    environment:
        - CROSSDOCK_CLIENTS=alpha,omega
        - CROSSDOCK_AXIS_BEHAVIOR=dance,sing

alpha:
    image: breerly/hello-server
    ports:
        - 8080
    environment:
        - HELLO_SLEEP=1
        - HELLO_PORT=8080
        - HELLO_MESSAGE=[{"status":"passed","output":"sup"}]

omega:
    image: breerly/hello-server
    ports:
        - 8080
    environment:
        - HELLO_PORT=8080
        - HELLO_MESSAGE=[{"status":"skipped","output":"sup"}]
