crossdock:
    image: yarpc/crossdock
    links:
        - alpha
        - omega
    environment:
        - CLIENTS=alpha,omega
        - AXIS_BEHAVIOR=dance,run
        - AXIS_SPEED=fast,slow

alpha:
    image: breerly/hello-server
    ports:
        - 8080
    environment:
        - HELLO_PORT=8080
        - HELLO_MESSAGE=ok

omega:
    image: breerly/hello-server
    ports:
        - 8080
    environment:
        - HELLO_PORT=8080
        - HELLO_MESSAGE=ok
